# Generated by Django 3.2.8 on 2021-10-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_auto_20210115_1116'),
        ('women', '0003_auto_20210930_1637'),
    ]

    operations = [
    ]
